version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/app # 인스턴스에서 파일이 저장될 위치
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  beforeInstall:
    - location: change_permission.sh
      timeout: 60
      runas: root

  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: ubuntu