server:
  port: 8080

spring:
  application:
    name: template

  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/template
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always