server:
  port: 8080

spring:
  application:
    name: running

  # MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/running-game
    username: ${LOCAL_DATABASE_ID}
    password: ${LOCAL_DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

jwt:
  secret:
    key: ${LOCAL_JWT_KEY}